# From https://github.com/openfaas/openfaas-operator/blob/master/artifacts/nodeinfo.yaml
#
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodeinfo
  namespace: openfaas-fn
spec:
  name: nodeinfo
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
  annotations:
    current-time: Mon  6 Aug 23:42:00 BST 2018
    next-time: Mon  6 Aug 23:42:00 BST 2019
  environment:
    output: "verbose"
    debug: "true"
  limits:
    cpu: "200m"
    memory: "512Mi"
  requests:
    cpu: "10m"
    memory: "128Mi"
  secrets:
   - faas-token
   - faas-key